### ISSUE TITLE
GMTK Meeting 0

### ISSUE THREAD

**Issue by Andrewyx** [Watercooled-Grapes/GMTK-2024#1]
### Getting Started
- [x] Introductions
- [x] GitHub setup & [Desktop](https://desktop.github.com/download/) 
- [x] Installing Unity 2022.3.39f1 
- [x] [GMTK](https://itch.io/jam/gmtk-2024) Timeline
### Team Structure:
- [x] **Developer** - Scripts Only, duplicate scenes to test features, comment your darn code please with `///` in JavaDoc style
- [x] **Designer** - Arts & VFX (Animation requires Unity usage)
- [x] **Writer** - Storyboarding
- [x] **Sound** - Music & SFX
- [x] **Presenter** - Itch page design, trailers, tutorials, credits etc.
- [x] **Integration** - World building, Scene design, adding assets & scripts to scenes, GitHub Admins

### GitHub Usage & File Sharing
- [x] Pull Requests ONLY (aside from integrators) 
- [x] One code review & integration approval to avoid Merge Errors (may change depending on urgency)
- [x] DO NOT MODIFY THE SAME PHYSICAL SCENE AT THE SAME TIME AS SOMEONE ELSE
- [x] Designers & Sound Artists drop assets into `GMTK-2024\Assets\some folder` & push (this would require others to pull their forks to use added assets and only open a PR when the whole feature is ready)
- [x] 2D Assets with [Kenney](https://www.kenney.nl/assets) or see more at [GMTK Tools & Assets](https://itch.io/jam/gmtk-2024#:~:text=Here%20are%20some%20places%20where%20you%20can%20find%20art%2C%20fonts%2C%20music%2C%20and%20sound%20effects%20for%20your%20games.)

### Game Design (General Direction, until theme announced)
- Magic Theme? 2D? Pixel Art, CRT, cartoon?
- Please use Prefabs & Scriptable objects as much as possible to reduce duplication and coupling
- See [Brackeys](https://www.youtube.com/@Brackeys/videos) for game jam vibes

**Comment by MikhaelWave** [comment]
fish
