### ISSUE TITLE
Create a way to choose whether a platform can be attached to with the tongue

### ISSUE THREAD

**Issue by axiev1** [Watercooled-Grapes/GMTK-2024#37]

**Comment by Lmh-java** [comment]
Hi, I thought when @Andrewyx designed this part, there is a flag for setting to attach to everything regardless OR we can set the mc to only grab objects in the layer number 9. Please refer to https://github.com/Watercooled-Grapes/GMTK-2024/blob/c6dc585209c31ca87b65036d65795d44d3eebc0b/Assets/GrapplingTongue/GrapplingGun.cs#L143-L155.
I have added this layer so we can simply add objects to this layer to set it attachable.
